# Generated by Django 6.0.4 on 2026-04-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestoreDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_type', models.CharField(choices=[('BACKUP', 'Backup'), ('RESTORE', 'Restore'), ('FULL', 'Full Drill')], default='BACKUP', max_length=20)),
                ('environment', models.CharField(default='Production', max_length=100)),
                ('runbook_version', models.CharField(blank=True, max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('rpo_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rto_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_drills_executed', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_drills_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['drill_type'], name='quality_com_drill_t_d47b54_idx'), models.Index(fields=['success'], name='quality_com_success_4e2371_idx'), models.Index(fields=['executed_at'], name='quality_com_execute_054e09_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('QUALITY', 'Quality'), ('SAFETY', 'Safety'), ('SECURITY', 'Security'), ('OPERATIONAL', 'Operational'), ('CLINICAL', 'Clinical')], default='QUALITY', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('INVESTIGATING', 'Investigating'), ('RCA_COMPLETE', 'Root Cause Complete'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status'], name='quality_com_status_93ef57_idx'), models.Index(fields=['incident_type'], name='quality_com_inciden_516022_idx'), models.Index(fields=['severity'], name='quality_com_severit_d6c004_idx'), models.Index(fields=['reported_at'], name='quality_com_reporte_1e9771_idx')],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=120)),
                ('policy_name', models.CharField(max_length=255)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('archive_after_days', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('owner_role', models.CharField(blank=True, max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module_name', 'policy_name'],
                'indexes': [models.Index(fields=['active'], name='quality_com_active_976f08_idx'), models.Index(fields=['module_name'], name='quality_com_module__7a3ff5_idx'), models.Index(fields=['next_review_at'], name='quality_com_next_re_517de8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SlaBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('LAB', 'Lab'), ('PHARMACY', 'Pharmacy'), ('BILLING', 'Billing'), ('IPD', 'Inpatient'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('WAIVED', 'Waived')], default='OPEN', max_length=20)),
                ('expected_at', models.DateTimeField()),
                ('breached_at', models.DateTimeField(auto_now_add=True)),
                ('owner_role', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_breaches_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_breaches_escalated_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-breached_at'],
                'indexes': [models.Index(fields=['status'], name='quality_com_status_3adb13_idx'), models.Index(fields=['severity'], name='quality_com_severit_6491a1_idx'), models.Index(fields=['expected_at'], name='quality_com_expecte_f151d4_idx')],
            },
        ),
    ]
