# Generated by Django 6.0.3 on 2026-03-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('ADMIN', 'Super Admin')], default='PATIENT', max_length=20),
        ),
    ]
