# Generated by Django 4.2 on 2026-03-21 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('SEMI_PRIVATE', 'Semi Private'), ('PRIVATE', 'Private'), ('ICU', 'ICU'), ('EMERGENCY', 'Emergency')], default='GENERAL', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=15)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='rooms.room')),
            ],
            options={
                'ordering': ['room__room_number', 'bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=15)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rooms.roombed')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_patients', to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='users.patientprofile')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
    ]
