# Generated by Django 6.0.3 on 2026-03-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('rooms', '0002_admissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='preferred_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_requests', to='clinical.doctor'),
        ),
    ]
