# Generated by Django 6.0.4 on 2026-05-16 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_nursingnote_nursingtask'),
        ('clinical', '0004_patientvisit_follow_up_completed_patientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_report', to='appointments.appointment'),
        ),
    ]
