# Generated by Django 6.0.3 on 2026-03-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ADMITTED', 'Admitted')], default='PENDING', max_length=15),
        ),
    ]
