# Generated by Django 6.0.3 on 2026-03-24 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_noshowpredictor_summary_waitinglist_notified_at_and_more'),
        ('users', '0006_patienthealthrecord_patientvitallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Describe current symptoms in detail.')),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('pain_level', models.PositiveSmallIntegerField(default=0)),
                ('has_fever', models.BooleanField(default=False)),
                ('has_breathing_issue', models.BooleanField(default=False)),
                ('has_chest_pain', models.BooleanField(default=False)),
                ('has_heavy_bleeding', models.BooleanField(default=False)),
                ('had_fainting_episode', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('P1', 'P1 - Immediate Emergency'), ('P2', 'P2 - Urgent Care Needed'), ('P3', 'P3 - Moderate Priority'), ('P4', 'P4 - Routine Care')], default='P4', max_length=2)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_triage_assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='users.patientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_triage_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
