# Generated by Django 6.0.4 on 2026-04-16 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_medicalreportanalysis'),
        ('clinical', '0002_doctorleave_approval_fields'),
        ('users', '0007_user_first_name_user_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('EXACT_NAME_DOB', 'Exact name and DOB'), ('SIMILAR_NAME_DOB', 'Similar name and DOB'), ('PHONE_MATCH', 'Phone number match'), ('EMAIL_MATCH', 'Email match')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='0.0 to 1.0 confidence of match')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(blank=True, help_text='Null=pending, True=confirmed duplicate, False=not a duplicate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('existing_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_existing', to='users.patientprofile')),
                ('new_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_new', to='users.patientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_patient_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score'],
                'unique_together': {('new_patient', 'existing_patient')},
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called to consultation'), ('IN_CONSULTATION', 'In consultation'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No show'), ('ARCHIVED', 'Archived')], default='WAITING', max_length=20)),
                ('source', models.CharField(choices=[('SCHEDULED', 'Scheduled appointment'), ('WALK_IN', 'Walk-in'), ('REFERRAL', 'Referral')], default='SCHEDULED', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_start', models.DateTimeField(blank=True, null=True)),
                ('consultation_end', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default='P4', max_length=2)),
                ('notes', models.TextField(blank=True, help_text='Receptionist notes')),
                ('no_show_reason', models.TextField(blank=True)),
                ('rebooking_attempted', models.BooleanField(default=False)),
                ('rebooking_contact_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='users.patientprofile')),
                ('triage_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.triageassessment')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['doctor', 'status', '-queued_at'], name='appointment_doctor__1795ef_idx'), models.Index(fields=['status', '-queued_at'], name='appointment_status_0cc75a_idx')],
            },
        ),
    ]
