# Generated by Django 6.0.3 on 2026-03-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='druginteraction',
            new_name='drug_checke_drug_a__52c110_idx',
            old_name='drug_checker_drug_a__d0cf5d_idx',
        ),
        migrations.RenameIndex(
            model_name='druginteraction',
            new_name='drug_checke_severit_8c1f1b_idx',
            old_name='drug_checker_severit_420f65_idx',
        ),
    ]
