# Generated by Django 6.0.3 on 2026-03-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('no_show_predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='noshowpredictionlog',
            new_name='no_show_pre_patient_f1e3a2_idx',
            old_name='no_show_pre_patient_e5ff4a_idx',
        ),
        migrations.RenameIndex(
            model_name='noshowpredictionlog',
            new_name='no_show_pre_doctor__42f0e0_idx',
            old_name='no_show_pre_doctor__840958_idx',
        ),
        migrations.RenameIndex(
            model_name='noshowpredictionlog',
            new_name='no_show_pre_risk_le_176bbd_idx',
            old_name='no_show_pre_risk_le_118977_idx',
        ),
    ]
