# Generated by Django 5.2.4 on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('inpatient', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('ot_room', models.CharField(max_length=80)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('pre_op_checklist', models.TextField(blank=True)),
                ('surgery_billing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthetist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_as_anesthetist', to='clinical.doctor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ot_schedules', to='users.user')),
                ('inpatient_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_schedules', to='inpatient.inpatientstay')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_schedules', to='users.patientprofile')),
                ('surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_as_surgeon', to='clinical.doctor')),
            ],
            options={
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['status', 'scheduled_start'], name='surgery_ots_status_8d386f_idx'), models.Index(fields=['ot_room', 'scheduled_start'], name='surgery_ots_ot_room_735eb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_steps', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('anesthesia_notes', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_note', to='surgery.otschedule')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_procedure_notes', to='users.user')),
            ],
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='PostOpNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_status', models.CharField(choices=[('STABLE', 'Stable'), ('OBSERVATION', 'Observation'), ('CRITICAL', 'Critical')], default='OBSERVATION', max_length=20)),
                ('pain_score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_op_notes', to='users.user')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_op_notes', to='surgery.otschedule')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
