# Generated by Django 6.0.4 on 2026-04-24 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otschedule',
            new_name='surgery_ots_status_90e405_idx',
            old_name='surgery_ots_status_8d386f_idx',
        ),
        migrations.RenameIndex(
            model_name='otschedule',
            new_name='surgery_ots_ot_room_4aec48_idx',
            old_name='surgery_ots_ot_room_735eb2_idx',
        ),
        migrations.AlterField(
            model_name='procedurenote',
            name='signed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
