# Generated by Django 6.0.3 on 2026-03-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinical', '0001_initial'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='General notes or diagnosis')),
                ('advice', models.TextField(blank=True, help_text="Doctor's advice to patient")),
                ('follow_up_date', models.DateField(blank=True, help_text='Next follow up date', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 10ml', max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once a day'), ('BD', 'Twice a day'), ('TDS', 'Three times a day'), ('QDS', 'Four times a day'), ('SOS', 'When needed'), ('STAT', 'Immediately')], default='OD', max_length=10)),
                ('duration', models.CharField(help_text='e.g. 5 days, 2 weeks', max_length=100)),
                ('timing', models.CharField(choices=[('BEFORE_MEAL', 'Before Meal'), ('AFTER_MEAL', 'After Meal'), ('WITH_MEAL', 'With Meal'), ('EMPTY_STOMACH', 'Empty Stomach'), ('BEDTIME', 'Bedtime'), ('ANY', 'Any Time')], default='AFTER_MEAL', max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
        ),
    ]
