# Generated by Django 6.0.3 on 2026-03-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('prescriptions', '0001_initial'),
        ('users', '0006_patienthealthrecord_patientvitallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Prescription expiry date', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='last_refill_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refill_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REFILLS_AVAILABLE', 'Refills Available'), ('NO_REFILLS', 'No Refills'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_remaining',
            field=models.IntegerField(default=0, help_text='Remaining refills (auto-calculated)'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_used',
            field=models.IntegerField(default=0, help_text='Number of refills already used'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_refills_allowed',
            field=models.IntegerField(default=0, help_text='0 = no refills allowed, -1 = unlimited'),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_names', models.TextField(help_text='Comma-separated brand names')),
                ('category', models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANTIHISTAMINE', 'Antihistamine'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTI_INFLAMMATORY', 'Anti-inflammatory'), ('PAIN_RELIEVER', 'Pain Reliever'), ('COLD_FLU', 'Cold & Flu'), ('ANTACID', 'Antacid'), ('ANTIDIABETIC', 'Antidiabetic'), ('ANTICOAGULANT', 'Anticoagulant'), ('STATIN', 'Statin'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, help_text='mg, ml, etc.', max_length=50)),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('pregnancy_category', models.CharField(blank=True, help_text='FDA pregnancy category: A-X', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['generic_name'],
                'unique_together': {('generic_name', 'strength')},
            },
        ),
        migrations.CreateModel(
            name='InteractionCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('interactions_found', models.IntegerField(default=0)),
                ('major_interactions', models.IntegerField(default=0)),
                ('moderate_interactions', models.IntegerField(default=0)),
                ('minor_interactions', models.IntegerField(default=0)),
                ('allergies_found', models.IntegerField(default=0)),
                ('cleared_by_doctor', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_interactions', to='clinical.doctor')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_checks', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Refill Requested'), ('APPROVED', 'Approved by Doctor'), ('REJECTED', 'Rejected'), ('FILLED', 'Filled by Pharmacy'), ('EXPIRED', 'Prescription Expired')], default='REQUESTED', max_length=15)),
                ('reason', models.CharField(blank=True, help_text='Reason for refill request', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Flag for urgent refills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refills', to='clinical.doctor')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_refills', to='prescriptions.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='prescriptions.prescription')),
                ('requested_by', models.ForeignKey(help_text='Patient or doctor requesting refill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('MILD', 'Mild (rash, itching)'), ('MODERATE', 'Moderate (swelling, difficulty breathing)'), ('SEVERE', 'Severe (anaphylaxis, life-threatening)')], max_length=10)),
                ('symptoms', models.TextField(help_text='Allergy symptoms experienced')),
                ('reaction_date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documented_allergies', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='prescriptions.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_allergies', to='users.patientprofile')),
            ],
            options={
                'unique_together': {('patient', 'generic_name')},
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('MAJOR', 'Major Interaction'), ('MODERATE', 'Moderate Interaction'), ('MINOR', 'Minor Interaction')], max_length=10)),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Contraindicated')], default=2, help_text='1-4, higher = more severe')),
                ('mechanism', models.TextField(help_text='How the drugs interact')),
                ('clinical_effect', models.TextField(help_text='What happens when combined')),
                ('management', models.TextField(help_text='What to do about this interaction')),
                ('evidence_rating', models.CharField(default='MODERATE', help_text='Quality of evidence: EXCELLENT, GOOD, MODERATE, POOR', max_length=20)),
                ('is_bidirectional', models.BooleanField(default=True, help_text='If true, both drug1+drug2 and drug2+drug1 interactions exist')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug1', to='prescriptions.drug')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug2', to='prescriptions.drug')),
            ],
            options={
                'ordering': ['-severity'],
                'unique_together': {('drug1', 'drug2')},
            },
        ),
        migrations.CreateModel(
            name='RefillReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_when_days_remaining', models.IntegerField(default=7, help_text='Remind patient when prescription has X days supply left')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_reminders', to='users.patientprofile')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_reminders', to='prescriptions.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'patient')},
            },
        ),
    ]
