# Generated by Django 6.0.3 on 2026-03-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0006_patienthealthrecord_patientvitallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Track partial payments', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Expected payment deadline', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='overdue_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='reminder_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('LAB_TEST', 'Lab Test'), ('ADMISSION', 'Hospital Admission'), ('CONSULTATION', 'Consultation'), ('OTHER', 'Other')], default='APPOINTMENT', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('OVERDUE', 'Overdue'), ('PARTIALLY_PAID', 'Partially Paid')], default='UNPAID', max_length=15),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('AUTO', 'Automatic Reminders'), ('MANUAL', 'Manual Reminders')], default='AUTO', max_length=10)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App Notification'), ('ALL', 'All Channels')], default='ALL', max_length=10)),
                ('first_reminder_days_before', models.IntegerField(default=3, help_text='Send reminder X days before due date')),
                ('second_reminder_days_after', models.IntegerField(default=2, help_text='Send reminder X days after due date if unpaid')),
                ('final_reminder_days_after', models.IntegerField(default=7, help_text='Final reminder X days after due date')),
                ('first_reminder_sent', models.BooleanField(default=False)),
                ('first_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('second_reminder_sent', models.BooleanField(default=False)),
                ('second_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('final_reminder_sent', models.BooleanField(default=False)),
                ('final_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disabled_reason', models.TextField(blank=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_reminders', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_number', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, 'Final')], help_text='Which reminder in sequence')),
                ('channel', models.CharField(max_length=10)),
                ('recipient', models.CharField(help_text='Email address, phone, etc.', max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed to Send'), ('BOUNCED', 'Bounced'), ('OPTIMAL', 'Optimal Delivery')], default='SENT', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('message_preview', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='payments.payment')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.paymentreminder')),
            ],
            options={
                'verbose_name_plural': 'Payment Reminder Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('policy_number', models.CharField(max_length=80)),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('coverage_percent', models.PositiveSmallIntegerField(default=0)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_verifications', to='users.patientprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'provider_name', 'policy_number')},
            },
        ),
    ]
