# Generated by Django 6.0.4 on 2026-05-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_refund_amount_refund_approval_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='khalti_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
