# Generated by Django 6.0.4 on 2026-04-16 05:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_nursingnote_nursingtask'),
        ('clinical', '0002_doctorleave_approval_fields'),
        ('prescriptions', '0002_pharmacy_prescription_expiry_date_and_more'),
        ('rooms', '0005_alter_admissionrequest_status'),
        ('users', '0009_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis', models.CharField(max_length=255)),
                ('admission_reason', models.TextField(blank=True)),
                ('care_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=15)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('actual_discharge_date', models.DateField(blank=True, null=True)),
                ('admission_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_stays', to='appointments.appointment')),
                ('admission_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_stays', to='rooms.admissionrequest')),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admitted_by', to=settings.AUTH_USER_MODEL)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_stays', to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_stays', to='users.patientprofile')),
                ('room_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_stays', to='rooms.roomassignment')),
            ],
            options={
                'ordering': ['-admission_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DischargePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateField(default=django.utils.timezone.localdate)),
                ('discharge_summary', models.TextField()),
                ('discharge_diagnoses', models.TextField(blank=True)),
                ('discharge_instructions', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('follow_up_provider', models.CharField(blank=True, max_length=255)),
                ('follow_up_specialty', models.CharField(blank=True, max_length=255)),
                ('doctor_signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('patient_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('nursing_clearance', models.BooleanField(default=False)),
                ('pharmacy_clearance', models.BooleanField(default=False)),
                ('billing_clearance', models.BooleanField(default=False)),
                ('final_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_discharges_signed', to=settings.AUTH_USER_MODEL)),
                ('patient_acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_discharges_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('inpatient_stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_package', to='inpatient.inpatientstay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_date', models.DateField(default=django.utils.timezone.localdate)),
                ('round_notes', models.TextField()),
                ('vital_assessment', models.TextField(blank=True)),
                ('current_status', models.CharField(blank=True, max_length=120)),
                ('orders', models.TextField(blank=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round_assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_rounds_assessed', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_rounds_signed', to=settings.AUTH_USER_MODEL)),
                ('inpatient_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rounds', to='inpatient.inpatientstay')),
            ],
            options={
                'ordering': ['-round_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dose_given', models.CharField(max_length=120)),
                ('route', models.CharField(blank=True, max_length=80)),
                ('scheduled_datetime', models.DateTimeField()),
                ('administered_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('GIVEN', 'Given'), ('OMITTED', 'Omitted'), ('DELAYED', 'Delayed')], default='SCHEDULED', max_length=12)),
                ('reason_not_given', models.TextField(blank=True)),
                ('deviations', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_mar_administered', to=settings.AUTH_USER_MODEL)),
                ('inpatient_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='inpatient.inpatientstay')),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mar_entries', to='prescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('scheduled_datetime', models.DateTimeField()),
                ('ot_room_number', models.CharField(blank=True, max_length=50)),
                ('indication', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inpatient_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='inpatient.inpatientstay')),
                ('surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_procedures', to='clinical.doctor')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('PROGRESS', 'Progress Note'), ('ROUND', 'Round Note'), ('NURSING', 'Nursing Note')], default='PROGRESS', max_length=20)),
                ('clinical_findings', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_progress_notes', to=settings.AUTH_USER_MODEL)),
                ('inpatient_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='inpatient.inpatientstay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inpatientstay',
            index=models.Index(fields=['status', '-admission_datetime'], name='inpatient_i_status_c4b558_idx'),
        ),
        migrations.AddIndex(
            model_name='inpatientstay',
            index=models.Index(fields=['patient', '-admission_datetime'], name='inpatient_i_patient_02e380_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyround',
            index=models.Index(fields=['round_date'], name='inpatient_d_round_d_92e2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyround',
            index=models.Index(fields=['inpatient_stay', '-round_date'], name='inpatient_d_inpatie_757965_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministrationrecord',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='inpatient_m_status_3731d9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministrationrecord',
            index=models.Index(fields=['inpatient_stay', '-scheduled_datetime'], name='inpatient_m_inpatie_95f492_idx'),
        ),
    ]
