# Generated by Django 5.2.4 on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeMedicationReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_medications', models.TextField(blank=True)),
                ('discharge_medications', models.TextField(blank=True)),
                ('reconciliation_notes', models.TextField(blank=True)),
                ('interactions_checked', models.BooleanField(default=False)),
                ('allergies_reviewed', models.BooleanField(default=False)),
                ('patient_counseled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inpatient_stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reconciliation', to='inpatient.inpatientstay')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_med_reconciliations', to='users.user')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
