# Generated by Django 6.0.3 on 2026-03-23 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoShowPredictor_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_appointments', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('actual_no_shows', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified'), ('PROMOTED', 'Promoted'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='NoShowPredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(choices=[('HEURISTIC', 'Rule-based Heuristic'), ('ML', 'Machine Learning')], default='HEURISTIC', max_length=10)),
                ('no_show_probability', models.FloatField(default=0.0, help_text='Probability of no-show (0-1)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (0-33%)'), ('MEDIUM', 'Medium Risk (33-66%)'), ('HIGH', 'High Risk (66-100%)')], default='LOW', max_length=10)),
                ('patient_history_score', models.IntegerField(default=0)),
                ('distance_score', models.IntegerField(default=0)),
                ('reminder_score', models.IntegerField(default=0)),
                ('time_score', models.IntegerField(default=0)),
                ('doctor_score', models.IntegerField(default=0)),
                ('weather_score', models.IntegerField(default=0)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('overbooking_compensation', models.BooleanField(default=False, help_text='If high no-show risk, overbookmultiple patients')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actually_no_showed', models.BooleanField(blank=True, null=True)),
                ('prediction_accuracy', models.FloatField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_prediction', to='appointments.appointment')),
            ],
        ),
    ]
