# Generated by Django 6.0.3 on 2026-03-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('lab', '0002_testbooking_collected_at_testbooking_collected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='critical_notification_sent',
            field=models.BooleanField(default=False, help_text='Track if critical values notification was sent to doctor'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='has_critical_values',
            field=models.BooleanField(default=False, help_text='Auto-flagged if any result item is critical'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Doctor who reviewed and approved results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_results', to='clinical.doctor'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Awaiting Lab Entry'), ('ENTERED', 'Results Entered'), ('REVIEWED', 'Under Doctor Review'), ('APPROVED', 'Approved by Doctor'), ('RELEASED', 'Released to Patient'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Workflow status of result', max_length=15),
        ),
    ]
