# Generated by Django 6.0.3 on 2026-03-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='heartriskassessment',
            new_name='heart_risk__patient_646c25_idx',
            old_name='heart_risk__patient_7047c1_idx',
        ),
        migrations.RenameIndex(
            model_name='heartriskassessment',
            new_name='heart_risk__risk_le_aa083d_idx',
            old_name='heart_risk__risk_le_151f15_idx',
        ),
    ]
