# Generated by Django 5.2.4 on 2026-04-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_mode', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('AMBULANCE', 'Ambulance'), ('REFERRAL', 'Referral'), ('POLICE', 'Police'), ('OTHER', 'Other')], default='WALK_IN', max_length=20)),
                ('triage_level', models.CharField(blank=True, choices=[('ESI_1', 'ESI 1 - Immediate'), ('ESI_2', 'ESI 2 - Emergent'), ('ESI_3', 'ESI 3 - Urgent'), ('ESI_4', 'ESI 4 - Less Urgent'), ('ESI_5', 'ESI 5 - Non Urgent')], max_length=10)),
                ('severity_priority', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('TRIAGED', 'Triaged'), ('IN_TREATMENT', 'In Treatment'), ('ADMITTED', 'Admitted'), ('TRANSFERRED', 'Transferred'), ('DISCHARGED', 'Discharged'), ('DECEASED', 'Deceased')], default='REGISTERED', max_length=20)),
                ('chief_complaint', models.TextField()),
                ('stabilization_notes', models.TextField(blank=True)),
                ('disposition_notes', models.TextField(blank=True)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_encounters', to='clinical.doctor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergency_encounters', to='users.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_encounters', to='users.patientprofile')),
            ],
            options={
                'ordering': ['-arrived_at'],
                'indexes': [models.Index(fields=['status', '-arrived_at'], name='emergency_en_status_57f81f_idx'), models.Index(fields=['severity_priority', '-arrived_at'], name='emergency_en_severit_b0e99a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(default=0)),
                ('triage_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='emergency.emergencyencounter')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_triage_entries', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('NURSING', 'Nursing'), ('DOCTOR', 'Doctor'), ('STABILIZATION', 'Stabilization'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_notes', to='users.user')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='emergency.emergencyencounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
