# Generated by Django 6.0.4 on 2026-04-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emergencyencounter',
            new_name='emergency_e_status_cf44d3_idx',
            old_name='emergency_en_status_57f81f_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencyencounter',
            new_name='emergency_e_severit_3eb3c9_idx',
            old_name='emergency_en_severit_b0e99a_idx',
        ),
    ]
