# Generated by Django 6.0.4 on 2026-04-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('ADMIN', 'Super Admin')], default='PATIENT', max_length=20),
        ),
    ]
