# Generated by Django 6.0.4 on 2026-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PHARMACIST', 'Pharmacist'), ('BILLING_OFFICER', 'Billing Officer'), ('INSURANCE_COORDINATOR', 'Insurance Coordinator'), ('ADMIN', 'Super Admin')], default='PATIENT', max_length=25),
        ),
    ]
