# Generated by Django 6.0.3 on 2026-03-05 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='e.g. Fasting Blood Sugar', max_length=200)),
                ('unit', models.CharField(blank=True, help_text='e.g. mg/dL, g/dL', max_length=50)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=2, help_text='Normal range minimum', max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=2, help_text='Normal range maximum', max_digits=10, null=True)),
                ('normal_text', models.CharField(blank=True, help_text='For text fields e.g. Negative', max_length=100)),
                ('field_type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text')], default='NUMBER', max_length=10)),
                ('is_required', models.BooleanField(default=False, help_text='If False, lab can leave it blank (shows — in report)')),
                ('order', models.IntegerField(default=0, help_text='Display order in report')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('preparation', models.TextField(blank=True, help_text='Instructions before test e.g. Fast for 8 hours')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.IntegerField(default=30, help_text='How long the test takes')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price at time of booking', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_bookings', to='users.patientprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lab.testtemplate')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('patient', 'template', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Lab technician notes')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lab/reports/')),
                ('is_released', models.BooleanField(default=False, help_text='Admin releases report to patient')),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.testbooking')),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Leave blank if test not done for this field', max_length=200, null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low'), ('ABNORMAL', 'Abnormal'), ('NOT_DONE', 'Not Done')], default='NOT_DONE', max_length=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testfield')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.testresult')),
            ],
        ),
        migrations.AddField(
            model_name='testfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lab.testtemplate'),
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_bookings', models.IntegerField(default=20, help_text='Max patients per day for this test')),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lab.testtemplate')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('template', 'day')},
            },
        ),
    ]
