# Generated by Django 6.0.3 on 2026-03-22 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='expected_report_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='specimen_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testfield',
            name='critical_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Critical high value threshold', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testfield',
            name='critical_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Critical low value threshold', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Authorized reviewer verified the report before release'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresultitem',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED_SAMPLE', 'Rejected Sample'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
