# Generated by Copilot on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_testresult_critical_notification_sent_and_more'),
        ('users', '0003_alter_user_role'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_recommendations', to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_recommendations', to='users.patientprofile')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_tests', to='users.user')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='lab.testtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='testrecommendation',
            unique_together={('patient', 'template', 'status')},
        ),
    ]
