# Generated by Django 6.0.4 on 2026-04-16 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_doctorleave_approval_fields'),
        ('lab', '0004_testrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalValueAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=True, help_text='Flag if this is truly critical')),
                ('urgency', models.CharField(choices=[('IMMEDIATE', 'Immediate (Life-threatening)'), ('URGENT', 'Urgent (Within 1 hour)'), ('PRIORITY', 'Priority (Within 4 hours)')], default='URGENT', max_length=15)),
                ('critical_fields', models.JSONField(default=list, help_text='List of critical field IDs and their values')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification_method', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('PHONE', 'Phone Call'), ('MANUAL', 'Manual Contact')], default='SMS', help_text='How the doctor was notified', max_length=50)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_notes', models.TextField(blank=True, help_text="Doctor's response or action taken")),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='Doctor who acknowledged the critical value', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_value_acknowledgments', to='clinical.doctor')),
                ('escalated_to', models.ForeignKey(blank=True, help_text='If not acknowledged, escalated to senior/admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_critical_values', to=settings.AUTH_USER_MODEL)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_acknowledgment', to='lab.testresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_id', models.CharField(help_text='Unique barcode for sample tracking', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Sample Collected'), ('IN_PROCESS', 'In Process'), ('VALIDATED', 'Validated'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected'), ('RECOLLECT', 'Recollect Requested')], default='COLLECTED', max_length=15)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Why sample was rejected')),
                ('recollect_reason', models.TextField(blank=True, help_text='Why recollection is needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Staff who collected the sample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_samples_collected', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Lab tech who processed the sample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_samples_processed', to=settings.AUTH_USER_MODEL)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='lab.testresult')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Lab supervisor who validated the sample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_samples_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_type', models.CharField(choices=[('CALIBRATION', 'Equipment Calibration'), ('QUALITY_CONTROL', 'Quality Control Check'), ('MAINTENANCE', 'Equipment Maintenance'), ('VALIDATION', 'Test Validation')], default='QUALITY_CONTROL', max_length=20)),
                ('result', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('CONDITIONAL', 'Conditional Pass')], default='PASSED', max_length=50)),
                ('details', models.TextField(help_text='QC details, calibration values, or findings')),
                ('reference_value', models.CharField(blank=True, max_length=100)),
                ('actual_value', models.CharField(blank=True, max_length=100)),
                ('deviation', models.CharField(blank=True, help_text='Acceptable deviation percentage or range', max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_logs_performed', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, help_text='Optional: Link to specific sample if QC relates to one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_logs', to='lab.labsample')),
                ('test_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_logs', to='lab.testtemplate')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
