export const ACCESS_MATRIX = {
  admin: ['ADMIN'],
  adminOperations: ['ADMIN', 'RECEPTIONIST'],
  finance: ['ADMIN', 'BILLING_OFFICER', 'INSURANCE_COORDINATOR'],
  compliance: ['ADMIN', 'QUALITY_COMPLIANCE_OFFICER'],
  audit: ['ADMIN'],
  security: ['ADMIN'],
  labWorkflow: ['ADMIN', 'RECEPTIONIST'],
  labOperations: ['ADMIN', 'LAB_TECHNICIAN'],
  criticalLabValues: ['ADMIN', 'DOCTOR', 'LAB_TECHNICIAN'],
  internalTools: ['ADMIN'],
} as const;

export const ROUTE_ACCESS: Record<string, readonly string[]> = {
  '/admin/analytics': ACCESS_MATRIX.admin,
  '/admin/doctors-management': ACCESS_MATRIX.admin,
  '/admin/drug-interactions': ACCESS_MATRIX.admin,
  '/admin/lab-workflow': ACCESS_MATRIX.labWorkflow,
  '/admin/manage-tests': ACCESS_MATRIX.admin,
  '/admin/rbac-verification': ACCESS_MATRIX.admin,
  '/admin/revenue-summary': ACCESS_MATRIX.admin,
  '/admin/schedules': ACCESS_MATRIX.admin,
  '/admin/security-monitoring': ACCESS_MATRIX.admin,
  '/admin/shifts': ACCESS_MATRIX.admin,
  '/admin/specializations': ACCESS_MATRIX.admin,
  '/admin/system-health': ACCESS_MATRIX.admin,
  '/admin/system-settings': ACCESS_MATRIX.admin,
  '/admin/users-management': ACCESS_MATRIX.admin,
  '/admin/patient-operations': ACCESS_MATRIX.adminOperations,
  '/audit-logs': ACCESS_MATRIX.audit,
  '/admin/audit-logs': ACCESS_MATRIX.audit,
  '/lab-dashboard': ACCESS_MATRIX.labOperations,
  '/lab-reports': ['ADMIN', 'DOCTOR', 'PATIENT', 'RECEPTIONIST', 'LAB_TECHNICIAN'],
  '/lab-reports/booking': ['ADMIN', 'DOCTOR', 'PATIENT', 'RECEPTIONIST', 'LAB_TECHNICIAN'],
  '/lab-reports/result': ['ADMIN', 'DOCTOR', 'PATIENT', 'RECEPTIONIST', 'LAB_TECHNICIAN'],
  '/receptionist/queue': ['ADMIN', 'RECEPTIONIST'],
  '/manage-leaves': ['DOCTOR'],
  '/reports': ['ADMIN', 'DOCTOR', 'RECEPTIONIST', 'BILLING_OFFICER', 'INSURANCE_COORDINATOR', 'QUALITY_COMPLIANCE_OFFICER'],
  '/tests': ACCESS_MATRIX.internalTools,
};
