export const ACCESS_MATRIX = {
  finance: ['ADMIN', 'BILLING_OFFICER', 'INSURANCE_COORDINATOR'],
  compliance: ['ADMIN', 'QUALITY_COMPLIANCE_OFFICER'],
  audit: ['ADMIN'],
  security: ['ADMIN'],
  emergency: ['ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST'],
  radiology: ['ADMIN', 'DOCTOR', 'RECEPTIONIST', 'LAB_TECHNICIAN'],
  radiologyHistory: ['ADMIN', 'DOCTOR', 'RECEPTIONIST', 'PATIENT'],
  ipd: ['ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST'],
  ipdRounds: ['ADMIN', 'DOCTOR'],
  pharmacy: ['ADMIN', 'PHARMACIST'],
  labWorkflow: ['ADMIN'],
  labOperations: ['ADMIN', 'LAB_TECHNICIAN'],
  criticalLabValues: ['ADMIN', 'DOCTOR', 'LAB_TECHNICIAN'],
  internalTools: ['ADMIN'],
} as const;

export const ROUTE_ACCESS: Record<string, readonly string[]> = {
  '/finance/dashboard': ACCESS_MATRIX.finance,
  '/finance/claims': ACCESS_MATRIX.finance,
  '/finance/denials': ACCESS_MATRIX.finance,
  '/finance/invoices': ACCESS_MATRIX.finance,
  '/finance/pre-auths': ACCESS_MATRIX.finance,
  '/finance/reconciliation': ACCESS_MATRIX.finance,
  '/compliance': ACCESS_MATRIX.compliance,
  '/audit-logs': ACCESS_MATRIX.audit,
  '/admin/audit-logs': ACCESS_MATRIX.audit,
  '/admin/security-monitoring': ACCESS_MATRIX.security,
  '/admin/lab-workflow': ACCESS_MATRIX.labWorkflow,
  '/emergency': ACCESS_MATRIX.emergency,
  '/radiology': ACCESS_MATRIX.radiology,
  '/radiology/history': ACCESS_MATRIX.radiologyHistory,
  '/ipd': ACCESS_MATRIX.ipd,
  '/ipd/doctor-rounds': ACCESS_MATRIX.ipdRounds,
  '/pharmacy/dashboard': ACCESS_MATRIX.pharmacy,
  '/pharmacy/dispense': ACCESS_MATRIX.pharmacy,
  '/pharmacy/inventory': ACCESS_MATRIX.pharmacy,
  '/lab/samples': ACCESS_MATRIX.labOperations,
  '/lab/qc-logs': ACCESS_MATRIX.labOperations,
  '/lab/critical-values': ACCESS_MATRIX.criticalLabValues,
  '/tests': ACCESS_MATRIX.internalTools,
};
