export const ACCESS_MATRIX = {
  admin: ['ADMIN'],
  adminOperations: ['ADMIN', 'RECEPTIONIST'],
  finance: ['ADMIN', 'BILLING_OFFICER', 'INSURANCE_COORDINATOR'],
  compliance: ['ADMIN', 'QUALITY_COMPLIANCE_OFFICER'],
  audit: ['ADMIN'],
  security: ['ADMIN'],
  emergency: ['ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST'],
  radiology: ['ADMIN', 'DOCTOR', 'RECEPTIONIST', 'LAB_TECHNICIAN'],
  radiologyHistory: ['ADMIN', 'DOCTOR', 'RECEPTIONIST', 'PATIENT'],
  ipd: ['ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST'],
  ipdRounds: ['ADMIN', 'DOCTOR'],
  pharmacy: ['ADMIN', 'PHARMACIST'],
  labWorkflow: ['ADMIN'],
  labOperations: ['ADMIN', 'LAB_TECHNICIAN'],
  criticalLabValues: ['ADMIN', 'DOCTOR', 'LAB_TECHNICIAN'],
  internalTools: ['ADMIN'],
} as const;

export const ROUTE_ACCESS: Record<string, readonly string[]> = {
  '/admin/analytics': ACCESS_MATRIX.admin,
  '/admin/doctors-management': ACCESS_MATRIX.admin,
  '/admin/drug-interactions': ACCESS_MATRIX.admin,
  '/admin/lab-workflow': ACCESS_MATRIX.admin,
  '/admin/manage-tests': ACCESS_MATRIX.admin,
  '/admin/rbac-verification': ACCESS_MATRIX.admin,
  '/admin/revenue-summary': ACCESS_MATRIX.admin,
  '/admin/room-analytics': ACCESS_MATRIX.admin,
  '/admin/rooms-management': ACCESS_MATRIX.admin,
  '/admin/schedules': ACCESS_MATRIX.admin,
  '/admin/security-monitoring': ACCESS_MATRIX.admin,
  '/admin/shifts': ACCESS_MATRIX.admin,
  '/admin/specializations': ACCESS_MATRIX.admin,
  '/admin/system-health': ACCESS_MATRIX.admin,
  '/admin/system-settings': ACCESS_MATRIX.admin,
  '/admin/users-management': ACCESS_MATRIX.admin,
  '/admin/approvals-center': ACCESS_MATRIX.adminOperations,
  '/admin/insurance-verification': ACCESS_MATRIX.adminOperations,
  '/admin/patient-operations': ACCESS_MATRIX.adminOperations,
  '/admin/queue-ops': ACCESS_MATRIX.adminOperations,
  '/finance/dashboard': ACCESS_MATRIX.finance,
  '/finance/claims': ACCESS_MATRIX.finance,
  '/finance/denials': ACCESS_MATRIX.finance,
  '/finance/invoices': ACCESS_MATRIX.finance,
  '/finance/pre-auths': ACCESS_MATRIX.finance,
  '/finance/reconciliation': ACCESS_MATRIX.finance,
  '/compliance': ACCESS_MATRIX.compliance,
  '/audit-logs': ACCESS_MATRIX.audit,
  '/admin/audit-logs': ACCESS_MATRIX.audit,
  '/emergency': ACCESS_MATRIX.emergency,
  '/radiology': ACCESS_MATRIX.radiology,
  '/radiology/history': ACCESS_MATRIX.radiologyHistory,
  '/ipd': ACCESS_MATRIX.ipd,
  '/ipd/doctor-rounds': ACCESS_MATRIX.ipdRounds,
  '/receptionist/queue': ['ADMIN', 'RECEPTIONIST'],
  '/manage-leaves': ['DOCTOR'],
  '/reports': ['ADMIN', 'DOCTOR', 'RECEPTIONIST', 'BILLING_OFFICER', 'INSURANCE_COORDINATOR', 'QUALITY_COMPLIANCE_OFFICER'],
  '/pharmacy/dashboard': ACCESS_MATRIX.pharmacy,
  '/pharmacy/dispense': ACCESS_MATRIX.pharmacy,
  '/pharmacy/inventory': ACCESS_MATRIX.pharmacy,
  '/lab/samples': ACCESS_MATRIX.labOperations,
  '/lab/qc-logs': ACCESS_MATRIX.labOperations,
  '/lab/critical-values': ACCESS_MATRIX.criticalLabValues,
  '/tests': ACCESS_MATRIX.internalTools,
};
