# Generated by Django 6.0.4 on 2026-04-16 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0002_pharmacy_prescription_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(help_text='Current quantity in stock')),
                ('unit', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('ML', 'Milliliter'), ('VIAL', 'Vial'), ('STRIP', 'Strip'), ('BOTTLE', 'Bottle'), ('BOX', 'Box')], max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField(auto_now_add=True)),
                ('is_near_expiry', models.BooleanField(default=False, help_text='Set when within 3 months of expiry')),
                ('is_expired', models.BooleanField(default=False, help_text='Set when past expiry date')),
                ('is_blocked', models.BooleanField(default=False, help_text='Blocked from dispensing if defective/recall')),
                ('is_controlled_drug', models.BooleanField(default=False, help_text='CII/IV/V narcotics/psychotropics')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'medication_name'],
            },
        ),
        migrations.CreateModel(
            name='DispensingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.IntegerField()),
                ('is_substituted', models.BooleanField(default=False, help_text='True if different from prescribed medication')),
                ('substitution_reason', models.TextField(blank=True, null=True)),
                ('substitution_approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISPENSED', 'Dispensed'), ('REFUSED', 'Refused'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refusal_reason', models.TextField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('contraindication_checked', models.BooleanField(default=False)),
                ('contraindication_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_dispensed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses_received', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_transactions', to='prescriptions.prescription')),
                ('substitution_approved_by', models.ForeignKey(blank=True, help_text='Doctor who approved substitution', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_approved', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.medicationinventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('NEAR_EXPIRY', 'Near Expiry'), ('EXPIRED', 'Expired'), ('RECALL', 'Recall Notice'), ('CONTRAINDICATION', 'Drug Interaction')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pharmacy.medicationinventory')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlledDrugLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('dea_schedule', models.CharField(choices=[('II', 'Schedule II'), ('III', 'Schedule III'), ('IV', 'Schedule IV'), ('V', 'Schedule V')], max_length=10)),
                ('log_type', models.CharField(choices=[('RECEIVED', 'Received from Supplier'), ('DISPENSED', 'Dispensed to Patient'), ('DESTROYED', 'Destroyed/Wasted'), ('RETURNED', 'Returned by Patient'), ('LOSS', 'Loss/Theft')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('transaction_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Any observations (seizure, spillage, etc.)', null=True)),
                ('patient', models.ForeignKey(blank=True, help_text='Patient if dispensed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_drugs_received', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_drug_logs_recorded', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_logs_witnessed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-recorded_at'],
                'indexes': [models.Index(fields=['dea_schedule', '-transaction_date'], name='pharmacy_co_dea_sch_a3c0b2_idx'), models.Index(fields=['recorded_by', '-transaction_date'], name='pharmacy_co_recorde_18c934_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicationinventory',
            index=models.Index(fields=['medication_name', 'is_expired'], name='pharmacy_me_medicat_28352f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinventory',
            index=models.Index(fields=['expiry_date'], name='pharmacy_me_expiry__fa5cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinventory',
            index=models.Index(fields=['is_controlled_drug'], name='pharmacy_me_is_cont_77cfb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationinventory',
            unique_together={('batch_number', 'medication_name', 'manufacturer')},
        ),
        migrations.AddIndex(
            model_name='dispensingtransaction',
            index=models.Index(fields=['patient', '-created_at'], name='pharmacy_di_patient_123cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensingtransaction',
            index=models.Index(fields=['status', '-created_at'], name='pharmacy_di_status_1ac8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensingtransaction',
            index=models.Index(fields=['dispensed_by', '-created_at'], name='pharmacy_di_dispens_e24a02_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyalert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='pharmacy_ph_alert_t_43edd5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyalert',
            index=models.Index(fields=['-created_at'], name='pharmacy_ph_created_539eaa_idx'),
        ),
    ]
